import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import TimeSeriesChart, { IAmountDateDataPoint } from '@/components/time-series-chart'
import { DateRangeSelector, IDateRange } from '@/components/date-range-selector'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  const [dateRange, setDateRange] = useState<IDateRange>({ start: new Date(), end: new Date() })
  const domain = [new Date(dateRange.start ?? 0).getTime(), new Date(dateRange.end ?? 0).getTime()]

  let { principal, rate, intervalType } = router.query;

  const data: IAmountDateDataPoint[] = [{
    principal: 337000,
    interest: 0,
    total: 337000,
    date: new Date(2023, 7, 20).getTime()
  },
  {
    principal: 337000,
    interest: 10,
    total: 337010,
    date: new Date(2023, 7, 21).getTime()
  },
  {
    principal: 337000,
    interest: 22,
    total: 337022,
    date: new Date(2023, 7, 22).getTime()
  },
  {
    principal: 337000,
    interest: 34,
    total: 337034,
    date: new Date(2023, 7, 23).getTime()
  }]

  return (
    <>
      <Head>
        <title>Loan Visualizer</title>
        <meta name="description" content="Tool to visualize the amount generated by a loan" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <TimeSeriesChart chartData={data} domain={domain} />
        <DateRangeSelector dateRange={dateRange} setDateRange={setDateRange} />
      </main>
    </>
  )
}
